Update zsh files

diff --git a/tag-tty/config/sh/functions b/tag-tty/config/sh/functions
--- a/tag-tty/config/sh/functions
+++ b/tag-tty/config/sh/functions
@@ -70,3 +70,23 @@ scode ()
         sudo touch $1 && code $1
     fi
 }
+
+# navigation
+up () {
+    local d=""
+    local limit="$1"
+
+    # Default to limit of 1
+    if [ -z "$limit" ] || [ "$limit" -le 0 ]; then
+        limit=1
+    fi
+
+    for ((i=1; i<=limit; i++)); do
+        d="../$d"
+    done
+
+    # perform cd. Show error if cd fails
+    if ! cd "$d"; then
+        echo "Couldn't go up $limit dirs.";
+    fi
+}
